Task/additional tests for validator gim 216
ghga-de/ghga-validator pull request #13
Opened 2023-08-01 09:42 UTC by galinatremper

2023-11-10 15:28 UTC, lkuchenb requested changes
Thanks, see comments inline. Apart form that, can we run the tests one level deeper without a report written to disk every time?

2023-11-10 15:28 UTC, lkuchenb commented on tests/test_object_iterator.py
> +        list1.append(elem)
Use list comprehension

2023-11-10 15:28 UTC, lkuchenb commented on tests/test_object_iterator.py
> +        list2.append(elem)
see above

2023-11-14 09:01 UTC, galinatremper commented
> Thanks, see comments inline. Apart form that, can we run the tests one level deeper without a report written to disk every time?

Well, we can certainly validate using one level deeper, but in this case we lose two-step validation, first json schema and then the rest. It would maybe make sense only for test cases, where we use only one plugin.

2024-02-21 08:47 UTC, lkuchenb approved these changes

2024-02-21 09:38 UTC, merged